version: '3.5'

services:
    mysql-server:
        image: mysql:8.0
        container_name: mysql-server
        volumes:
             - mysql_datadir:/var/lib/mysql:rw
        env_file:
            - .env_mysql
        restart: unless-stopped
        command: -d mysql:8.0
        command: --character-set-server=utf8
        command: --collation-server=utf8_bin
        command: --default-authentication-plugin=mysql_native_password
        
    zabbix-server:
        image: zabbix/zabbix-server-mysql:centos-5.4-latest
        container_name: zabbix-server
        ports:
            - "10051:10051"
            - "10052:10052"
        volumes:
            - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
            - /usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
            - /var/lib/zabbix/export:/var/lib/zabbix/export:rw
            - /var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
            - /var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
            - /var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
            - /var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
            - /snmptraps:/var/lib/zabbix/snmptraps:rw    
        restart: unless-stopped
        env_file:
            - .env_mysql_db
            - .env_srv_zabbix   
        
            
    zabbix-frontend:
        image: zabbix/zabbix-web-nginx-mysql:alpine-5.4-latest
        container_name: zabbix-frontend
        ports:
            - "8081:80"
            - "8082:8080"
        env_file:
             - .env_web_zabbix
            
        restart: unless-stopped
        
volumes:
    mysql_datadir:
        name: mysql_volume



