version: '3.5'

services:
    mysql-server:
        image: mysql:8.0
        container_name: mysql-server
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=zabbix
            - MYSQL_ROOT_PASSWORD=root_pwd
        command: --name "mysql-server"
        command: --restart unless-stopped
        command: --character-set-server=utf8"
        command: --collation-server=utf8_bin
        command: --default-authentication-plugin=mysql_native_password
